### ISSUE TITLE
Password hashing is unconditional (possible Denial of Service attack)

### ISSUE THREAD

**Issue by DataWraith** [slashdotdash/conduit#11]
Hi.

I've been following along with the book and really like it so far. However, from what I understand, there might be a Denial of Service problem with the password hashing. 

Since the password is hashed unconditionally and is not restricted in length, someone could upload a password that is a couple of megabytes in size, and the server would be quite busy hashing that.

The simplest solution I could come up with was to restrict the password length using a `byte_size(password) <= 64` guard clause on `hash_password/1`, but I'd love to hear about a more elegant way of doing this, especially if it lets you enforce a minimum password length as well.

**Comment by slashdotdash** [comment]
It seems that [input size has no real affect on password hashing time](https://crypto.stackexchange.com/questions/32688/how-does-hash-speed-vary-based-on-string-length), instead for a password hashing function such as bcrypt as used in this app the work factor is by far the biggest determining factor. You can adjust the work factor of the bcrypt hash function in the config file. 

Another point is that due to the Erlang’s soft-real-time features it should not be possible for a single process to cause a denial of service. Each process is given a finite amount of CPU time by the scheduler which is determined by the number of reductions (function calls). 

With that said, it makes sense to limit the password size anyway. I would use validation on the command field (e.g. password for register user command) using the Vex library as existing validation rules.

**Comment by DataWraith** [comment]
Hi, thanks for the quick response. 

Strange, I had previously heard that using a large input size would slow the password hash functions down quite badly.  I'll close the issue then. 

Using Vex on the registration command was actually my first idea, but that's not as simple as I thought -- the password is deleted after being hashed, so the validation middleware has nothing to work with after the command is dispatched. I managed to make it work by deferring the deletion of the password until later when the aggregate functions (apply/execute) get their turn, but I'm not yet confident that was the correct thing to do.

**Comment by slashdotdash** [comment]
Yes, good point about the password field being cleared before validation middleware is involved. You could add a field to the command for the original password length which is set in the `hash_password` function before the password is wiped. That would allow validation to be configured on the password length field to ensure it is less than some defined maximum.

**Comment by slashdotdash** [comment]
The reason for excluding the plain text password from the command is to ensure it doesn’t get mistakenly included in any command auditing or logs. However if you use the Commanded audit middleware it now [has support for filtering sensitive command fields](https://github.com/commanded/commanded-audit-middleware/pull/3) which includes passwords by default.

**Comment by DataWraith** [comment]
Thanks, that's good to know. :)
