### ISSUE TITLE
Query composition

### ISSUE THREAD

**Issue by harjis** [slashdotdash/conduit#30]
Hi!

I happened to come across this project while studying different implementations on CQRS. This is not really an issue but more of a question as I happened to notice that query composition is not used and I wondered if there is a reason for this? As an example this [code](https://github.com/slashdotdash/conduit/blob/master/lib/conduit/blog/queries/article_comments.ex).

```elixir
defmodule Conduit.Blog.Queries.ArticleComments do
  import Ecto.Query

  alias Conduit.Blog.Projections.Comment

  def new(article_uuid) do
    from c in Comment,
    where: c.article_uuid == ^article_uuid,
    order_by: [desc: c.commented_at]
  end
end
```

With query composition this could be written like:

```elixir
defmodule Conduit.Blog.Queries.ArticleComments do
  import Ecto.Query

  alias Conduit.Blog.Projections.Comment

  def new(article_uuid) do
    Comment
    |> Comment.with_article_uuid(article_uuid)
    |> Comment.ordered_by_commented_at()
  end
end

defmodule Conduit.Blog.Projections.Comment do
  use Ecto.Schema

  import Ecto.Query

  #....

  def with_article_uuid(query, article_uuid) do
    query
    |> where([c], c.article_uuid == ^article_uuid)
  end

  def ordered_by_commented_at(query) do
    query
    |> order_by([c], desc: c.commented_at)
  end
end
```

Some of the queries do not return queryable but a tuple. By a quick look it seems that all of these also have pagination logic in it which I guess is the reason for the tuple. Instead of this these could return a queryable too in which case the pagination logic could be removed and replaced with a 3rd party one like this: https://github.com/drewolson/scrivener_ecto

Any thoughts on this?

**Comment by slashdotdash** [comment]
I've tried to keep the read model projections, such as the `Conduit.Blog.Projections.Comment` module, as succinct as possible. They really just define the Ecto `schema`. Any logic for querying and filtering is written in the query module, such as the `ArticleComments`, which is designed to support a single query pattern needed by the application. Usually it's used to display some UI and therefore the query module can be tailored to the predicates and pagination required. 

Why do I want as little logic as possible in the projection modules? It's because they shouldn't have any behaviour nor be a catch-all location for querying functionality. Read models are intended to be relatively dumb data structs and little else.

The approach you've shown is perfectly valid so if you prefer that style then use it!

**Comment by harjis** [comment]
Thanks for quick answer! Would you say this is more of a ideological difference or is there some concrete drawbacks that I'm just not seeing? I suppose code sharing is harder / not possible with this approach but is it so that is the intention?

**Comment by slashdotdash** [comment]
It's mostly an aesthetic decision; I'm fine with either approach. I learn more towards "skinny" projection modules so that they don't become too bloated, which can often be the case with these types of database-backed models.

**Comment by harjis** [comment]
Right. Thanks for the clarifications! I'll close the issue as I'm not proposing any changes to the project.
